### PR TITLE
fix: properly trim HTML length

### LINKED ISSUE #88: bug: Error: can't parse entities
Link to Sentry issues:
- https://sentry.io/share/issue/97a49e310ce145cab5342f72018948a1/
- https://sentry.io/share/issue/047208106eaf4df99378329c6e4b2711/

Occurred when doing these on a public supergroup:
- `/laodeai the art of productive laziness`
- `/search chrome download via blob`

A bit of help:
```
http      GET    https://en.wikipedia.org/wiki/Laziness [200] info 05:59:21
http      POST   https://api.telegram.org/-redacted-/sendMessage [400] info 05:59:21
exception Error: 400: Bad Request: can't parse entities: Unmatched end tag at byte offset 490, expected "</i>", found "</a>" error 05:59:21
```

```
http      GET    https://html.duckduckgo.com/html/?kp=1&q=chrome+download+via+blob [200] info 08:15:39
http      POST   https://api.telegram.org/-redacted-/sendMessage [400] info 08:15:39
exception Error: 400: Bad Request: can't parse entities: Unsupported start tag "script" at byte offset 1893 error 08:15:39
```

If you need more information, feel free to ask it here or in the Telegram group. Good luck.

### PR DESCRIPTION
**Pull request by elianiva**
close #88

image
image
image
image

### CODE REVIEW

**Review by artileda — APPROVED** [review]
Looks neat and good, ready to merge.

File: src/utils/trimHtml.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+ */
+const closest = (needle, haystack) =>
+  haystack
+    .filter((x) => x > needle)
+    .reduce((curr, acc) => {
+      const aDiff = Math.abs(curr - needle);
+      const bDiff = Math.abs(acc - needle);
+
+      return bDiff < aDiff ? acc : curr;
+    });
```
Comment (aldy505) [inline src/utils/trimHtml.js:17]: Ini oke kah tanpa value initializer?

**Review by aldy505 — APPROVED** [review]
