### PR TITLE
fix: even safer search

### LINKED ISSUE #135: cleaner safe `/search`
try to make the input and possible output as lowercase first, then test it against the data on mongodb to provide even cleaner safe search. 

cc @elianiva

### PR DESCRIPTION
**Pull request by aldy505**
closes #135 

the entry description wasn't sanitized before.

also added prevention for this case:

image

### CODE REVIEW

File: src/services/search/filter.js [hunk 1]
```diff
@@ -40,10 +41,11 @@ export async function cleanFilter(search, mongo) {
 
   const result = search.filter((o) => {
     for (const match of dedupeMatches) 
-      if (o.href.includes(match) || o.title.includes(match)) 
+      if (o.href.toLowerCase().includes(match) || 
+        o.title.toLowerCase().includes(match) || 
+        o.snippet.toLowerCase().includes(match))
```
Comment (elianiva) [inline src/services/search/filter.js:46]: jadi pengen nambahin https://eslint.org/docs/rules/operator-linebreak biar bisa gini, tapi nanti ae lah

```suggestion
      if (o.href.toLowerCase().includes(match)
          || o.title.toLowerCase().includes(match) 
          || o.snippet.toLowerCase().includes(match)) 
```
